import React, { createContext, useContext, useEffect, useState } from 'react';
import { collection, onSnapshot, addDoc, doc, deleteDoc, updateDoc, writeBatch } from 'firebase/firestore';
import { db, auth } from '../firebaseConfig';
import { useAuth } from './AuthContext';

const ScheduleContext = createContext(undefined);
const COLLECTION = 'schedules';

// Start of today, local time — the "floor" any overdue opening item gets
// rolled forward to.
function startOfToday() {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  return d.getTime();
}

export function ScheduleProvider({ children }) {
  const [entries, setEntries] = useState([]);
  const { user } = useAuth();

  useEffect(() => {
    if (!user) {
      setEntries([]);
      return;
    }
    const unsubscribe = onSnapshot(collection(db, COLLECTION), (snapshot) => {
      const list = snapshot.docs.map((d) => {
        const data = d.data();
        return {
          id: d.id,
          locationId: data.locationId,
          title: data.title,
          dateTime: data.dateTime,
          note: data.note ?? '',
          authorName: data.authorName,
          authorUid: data.authorUid ?? null,
          timestamp: data.timestamp,
          // Present only on entries generated by the Opening Checklist —
          // regular calendar entries just won't have these fields at all.
          // Storing checklist items as schedule entries (rather than a
          // separate collection with its own copy) is what guarantees the
          // Checklist screen and the Calendar can never drift out of sync —
          // there's only ever one document per task.
          openingItem: data.openingItem ?? false,
          openingItemType: data.openingItemType ?? null, // 'timeline' | 'setup'
          openingSection: data.openingSection ?? null,
          openingFields: data.openingFields ?? null, // { company, accountNumber, contact } — setup items only
          setupKey: data.setupKey ?? null, // links a setup item back to its INITIAL_SETUP_ITEMS entry, for dependency lookups
          templateId: data.templateId ?? null, // which city template produced this item
          // The permit or certificate itself: { url, path, name, uploadedAt,
          // uploadedBy }. Lives on the task that produced it, and gets copied
          // to the renewal record on sign-off so it's there at renewal time.
          document: data.document ?? null,
          renewalItem: data.renewalItem ?? false, // the migrated license/permit's initial "get this" calendar task
          renewalType: data.renewalType ?? null, // matches a type in renewalTypes.js
          done: data.done ?? false,
          doneBy: data.doneBy ?? null,
          doneAt: data.doneAt ?? null,
          // Set the first time an item goes overdue and stays set (even as
          // dateTime keeps getting rolled to today) until it's signed off —
          // this is what makes the urgent badge distinct from something
          // that's simply due today for the first time.
          attentionFlag: data.attentionFlag ?? false,
        };
      });
      setEntries(list);

      // Roll forward any un-signed-off opening item whose date has passed.
      // Runs once per snapshot per session (guarded so it doesn't refire on
      // every render) and is safe if two devices both run it — worst case
      // is a redundant, idempotent write.
      const today = startOfToday();
      const overdue = list.filter((e) => (e.openingItem || e.renewalItem) && !e.done && e.dateTime < today);
      if (overdue.length > 0) {
        const batch = writeBatch(db);
        overdue.forEach((e) => {
          batch.update(doc(db, COLLECTION, e.id), { dateTime: today, attentionFlag: true });
        });
        batch.commit().catch(() => {
          // Fine to lose this race silently — another client's snapshot
          // will pick up the same overdue set and retry.
        });
      }
    });
    return unsubscribe;
  }, [user]);

  const addEntry = async (params) => {
    await addDoc(collection(db, COLLECTION), {
      ...params,
      authorUid: auth.currentUser?.uid ?? null,
      timestamp: Date.now(),
    });
  };

  const deleteEntry = async (id) => {
    await deleteDoc(doc(db, COLLECTION, id));
  };

  const updateEntry = async (id, updates) => {
    await updateDoc(doc(db, COLLECTION, id), updates);
  };

  // Marks (or unmarks) an opening-checklist item done — since it IS the
  // calendar entry, this is the exact same action whether triggered from
  // the Checklist screen or the Calendar screen.
  const toggleOpeningItemDone = async (id, done, doneByName) => {
    await updateDoc(doc(db, COLLECTION, id), {
      done,
      doneBy: done ? doneByName : null,
      doneAt: done ? Date.now() : null,
    });
  };

  const getByLocation = (locationId) =>
    entries.filter((e) => e.locationId === locationId).sort((a, b) => a.dateTime - b.dateTime);

  const getByLocations = (locationIds) =>
    entries.filter((e) => locationIds.includes(e.locationId)).sort((a, b) => a.dateTime - b.dateTime);

  const getOpeningItemsByLocation = (locationId) =>
    entries.filter((e) => e.locationId === locationId && e.openingItem).sort((a, b) => a.dateTime - b.dateTime);

  return (
    <ScheduleContext.Provider
      value={{
        entries,
        addEntry,
        updateEntry,
        deleteEntry,
        getByLocation,
        getByLocations,
        getOpeningItemsByLocation,
        toggleOpeningItemDone,
      }}
    >
      {children}
    </ScheduleContext.Provider>
  );
}

export function useSchedule() {
  const ctx = useContext(ScheduleContext);
  if (!ctx) throw new Error('useSchedule must be used within ScheduleProvider');
  return ctx;
}
